### ISSUE TITLE
RTX A5000 missing from the list

### ISSUE THREAD

**Issue by kgarg8** [mlco2/impact#40]
Please push A5000 on the list.

**Comment by vict0rsch** [comment]
Depending on how fast you need this you may consider opening a PR to add that GPU to the list in https://github.com/mlco2/impact/blob/master/data/gpus.csv and fill in the columns 

<img width="807" alt="SCR-20230122-o0s" src="https://user-images.githubusercontent.com/9283470/213943316-bc771931-28a3-4880-a472-8735774ae95b.png">

Otherwise I'll do it sometime next week

**Comment by kgarg8** [comment]
Opened a [PR](https://github.com/mlco2/impact/pull/41)

**Comment by vict0rsch** [comment]
Merged. Thanks @kgarg8
