### ISSUE TITLE
This website makes me feel bad about my research

### ISSUE THREAD

**Issue by gabrielhuang** [mlco2/impact#6]
What should I do about it ?

**Comment by vict0rsch** [comment]
It's not only about you personally: visit our "act" section to do what you can to limit your emissions while doing your impactful research but remember you can also have an impact by pushing larger organization to take this into account. Use our latex template to report your emission spread this concern so that you share the burden :) The goal here is not to make you feel guilty, but responsible. And to support the many groups which work toward more energy-efficient AI

**Comment by vict0rsch** [comment]
You may close the issue if and when you feel your concern's been addressed :)

**Comment by gabrielhuang** [comment]
Thank you, I do realize now that the first step for improvement is defining the metrics we care about.
